- name: Play Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play Variables from Files
  hosts: localhost
  ## vars_files works only on play level
  vars_files:
    - var.yml
  tasks:
    - name: Print Play Variable from File
      ansible.builtin.debug:
        msg: URL = {{ URL }}

